### ISSUE TITLE
great work!where can i get the teacher model pram?

### ISSUE THREAD

**Issue by FelixZhang7** [szq0214/MEAL-V2#1]

**Comment by szq0214** [comment]
Hi @FelixZhang7, thanks for your interest in our work, you can directly run our script and it will download the teacher models automatically.

**Comment by FelixZhang7** [comment]
@szq0214 thanks，I see timm.create_model in your code，but what should i do if i want to use my own pretrained model as teather model ?

**Comment by szq0214** [comment]
Hi @FelixZhang7, there is a flag "--teacher-state-file" to support this function, but you may need to modify several lines of the code. In models/model_factory.py, comment line 66 and uncomment 67. Make sure the loading way by line 27 is suitable for your pre-trained models, you can refer to https://github.com/pytorch/examples/blob/master/imagenet/main.py#L177 if you have the same structure of the pytorch pre-trained checkpoint (we only save state_dict in the model). I will update our code to support this very soon.
