### ISSUE TITLE
Paper Inconsistency with Code

### ISSUE THREAD

**Issue by verbiiz** [szq0214/MEAL-V2#10]
The initial LR in your "Experimental Settings" section in the [ARXIV paper](https://arxiv.org/pdf/2009.08453.pdf) says you use `0.01`.

![Screenshot from 2020-11-09 16-07-33](https://user-images.githubusercontent.com/26421036/98611283-81a63100-22a6-11eb-9f03-3711eaaa07de.png)

Although, analyzing your [source code your ResNet50 model](https://github.com/szq0214/MEAL-V2/blob/316776a87507a524378696537fef15c6fac2d0ef/models/resnet50.py#L8) uses an initial LR of `0.1`.

![Screenshot from 2020-11-09 16-08-03](https://user-images.githubusercontent.com/26421036/98611290-836ff480-22a6-11eb-99d7-5217b7a9df0c.png)

I believe the paper is mistaken, as running your source code seems to be fine. In fact, the whole experimental setup is incorrect in comparison to this LR_REGIME.

**Comment by szq0214** [comment]
@McCrearyD, we did not use this file to build our model, our learning rate schedule is at https://github.com/szq0214/MEAL-V2/blob/316776a87507a524378696537fef15c6fac2d0ef/models/model_factory.py#L72 I will remove it to avoid misleading.

**Comment by verbiiz** [comment]
> @McCrearyD, we did not use this file to build our model, our learning rate schedule is at
> 
> https://github.com/szq0214/MEAL-V2/blob/316776a87507a524378696537fef15c6fac2d0ef/models/model_factory.py#L72
> 
> I will remove it to avoid misleading.

Ah, very good. Thank you!
