### ISSUE TITLE
What is the performance of the teacher model

### ISSUE THREAD

**Issue by PyJulie** [szq0214/MEAL-V2#14]
As the results of table II in your paper, trainning from scratch using Resnet obbtains 76.51% accuracy. When the input size is 224 x 224,  the student model Resnet 50 obtains 80.67% accuracy with senet154 and resnet152 v1 applied as teacher models through MEAL-V2. 
So I am wondering what is the performance of the pre-trained teacher model since they are with larger and more effcitive architectures?

**Comment by szq0214** [comment]
@PyJulie I just did a test on them and the accuracies are senet154: Acc@1 81.378 Acc@5 95.386; resnet152_v1s: Acc@1 80.860 Acc@5 95.348. These results are close and similar to the reported ones in timm.

**Comment by PyJulie** [comment]
Thanks!
