### ISSUE TITLE
使用mobilenet_v2的预训练参数，top1的精度从0开始，请问这正常嘛？

### ISSUE THREAD

**Issue by yukaizhou** [szq0214/MEAL-V2#15]
你好，感谢您优秀的工作。我使用ImageNet预训练的teacher模型为resnet101和resnet152， student模型为ImageNet的预训练模型mobilenet_v2，但是刚开始训练的top1精度为0，请问这正常嘛？我将student换成shufflenet_x1_0，top1精度为73.2%。谢谢您的回复！

**Comment by szq0214** [comment]
@yukaizhou 不太正常，这种情况很有可能是预训练的模型没有加载成功

**Comment by yukaizhou** [comment]
好的  那我再重新试下 谢谢回复！
