### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by yukaizhou** [szq0214/MEAL-V2#16]
你好，感谢您优秀的工作。在论文中，您是利用big model蒸馏big model, lite model蒸馏lite model，那为什么没有做big model蒸馏 lite model的实验呢？或者说有其他的问题？谢谢您的回复！！！

**Comment by szq0214** [comment]
@yukaizhou MobileNet V3-Small 0.75/1.0, Large 1.0, EfficientNet-B0这些实验都属于big model蒸馏lite model，我们没有做lite蒸馏lite, 而且结果上看, teacher越大，student越小，提升越明显
