### ISSUE TITLE
can not download model

### ISSUE THREAD

**Issue by KeyKy** [szq0214/MEAL-V2#17]
I can not download models from onedrive. Could someone upload them to BaiduYun?

**Comment by szq0214** [comment]
@KeyKy here is the BaiduYun link: https://pan.baidu.com/s/1doEnaDhwfV2ZP51RTNqcHA and pw: 2bq3
You can also download the models from GitHub directly: https://github.com/szq0214/MEAL-V2/releases/tag/v1.0.0

**Comment by KeyKy** [comment]
Thanks!
