### ISSUE TITLE
why are top1 and top5  both 0.0?

### ISSUE THREAD

**Issue by zylxadz** [szq0214/MEAL-V2#19]
I parpared my own data according to the imagenet format (train/ and val/ folders contain different classes of image folders.)and trained the model.
But after 60 epoch ,the top1 and top5 are both still 0.0
What could be the problem？Looking forward to your reply.Thanks!

INFO 2021-01-28 22:14:55,943:	 Epoch: [59][141/181]	Time 1.25 (6.42)   Data 0.00 (0.14)   G_Loss 3.085 {3.283, 3.279}    D_Loss 0.347 {0.347, 0.347}    Top-1 0.00 {0.00, 0.00}    Top-5 0.00 {0.00, 0.00}    LR 0.01000
INFO 2021-01-28 22:15:20,853:	 Epoch: [59][161/181]	Time 1.24 (5.78)   Data 0.00 (0.12)   G_Loss 3.101 {3.267, 3.255}    D_Loss 0.347 {0.347, 0.347}    Top-1 0.00 {0.00, 0.00}    Top-5 0.00 {0.00, 0.00}    LR 0.01000
INFO 2021-01-28 22:15:45,187:	 Epoch: [59][181/181]	Time 0.65 (5.28)   Data 0.00 (0.11)   G_Loss 3.335 {3.266, 3.253}    D_Loss 0.347 {0.347, 0.347}    Top-1 0.00 {0.00, 0.00}    Top-5 0.00 {0.00, 0.00}    LR 0.01000
INFO 2021-01-28 22:15:45,965:	 Epoch: [59] -- TRAINING SUMMARY	Time 955.00   Data 19.59   G_Loss 3.266     D_Loss 0.347     Top-1 0.00    Top-5 0.00

**Comment by szq0214** [comment]
@zylxadz Can you check the category mapping between your train and val sets? Also, are your teachers pre-trained on your dataset in advance?

**Comment by zylxadz** [comment]
I will check again.Thanks for your prompt reply！
