### ISSUE TITLE
torch.nn.DataParallel error

### ISSUE THREAD

**Issue by gentlebreeze1** [szq0214/MEAL-V2#22]
trian error :+1: RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!
how to solve this problem? i use to(device),but it do not work.error in @szq0214 
![image](https://user-images.githubusercontent.com/27668596/123934544-638a5f80-d961-11eb-9353-5bcb38c53d11.png)

**Comment by szq0214** [comment]
@gentlebreeze1 I did not meet this error before, are you running with our default codes? I guess your GPUs for loading the model and running the model are different, so you encounter this error.

**Comment by gentlebreeze1** [comment]
> @gentlebreeze1 I did not meet this error before, are you running with our default codes? I guess your GPUs for loading the model and running the model are different, so you encounter this error.

i train my own model,use 
`ckpt={'epoch':epoch+1,
                      'state_dict':net.module.state_dict(),
                      'optimizer':optimizer.param_groups[0]['lr']}
                torch.save(ckpt, weights_path)`
and load 
` model = _create_model(model_name, teacher=False, pretrain=True)
    checkpoint = torch.load(state_file)
    if 'state_dict' in checkpoint:
        model.load_state_dict(checkpoint['state_dict'])
    else:
        model.load_state_dict(checkpoint)
    `
I don’t think it’s a problem with model loading，the erorr occurred on Discriminator.conv1

**Comment by gentlebreeze1** [comment]
i change as follows, it works.Will it affect the final  result?@szq0214
class discriminatorLoss(nn.Module):
    def __init__(self, outputs_size,K=2, loss=nn.BCEWithLogitsLoss()):
        super(discriminatorLoss, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=outputs_size, out_channels=outputs_size // K, kernel_size=1, stride=1,
                               bias=True)
        outputs_size = outputs_size // K
        self.conv2 = nn.Conv2d(in_channels=outputs_size, out_channels=outputs_size // K, kernel_size=1, stride=1,
                               bias=True)
        outputs_size = outputs_size // K
        self.conv3 = nn.Conv2d(in_channels=outputs_size, out_channels=2, kernel_size=1, stride=1, bias=True)
        self.loss = loss

    def forward(self, outputs, targets):
        inputs = [torch.cat((i, j), 0) for i, j in zip(outputs, targets)]
        inputs = torch.cat(inputs, 1)
        batch_size = inputs.size(0)
        target = torch.FloatTensor([[1, 0] for _ in range(batch_size // 2)] + [[0, 1] for _ in range(batch_size // 2)])
        target = target.to(inputs[0].device)
        inputs=inputs[:,:,None,None]
        out = F.relu(self.conv1(inputs))
        out = F.relu(self.conv2(out))
        out = F.relu(self.conv3(out))
        output = out.view(out.size(0), -1)
        res = self.loss(output, target)
        return res

**Comment by gentlebreeze1** [comment]
my pre model size is 59.7M ,why save model size is 109M? after distillation ,model will grow bigger?@szq0214

**Comment by szq0214** [comment]
Hi @gentlebreeze1 The model size will not grow after distillation, I guess you saved other parameters in your checkpoint.
