### ISSUE TITLE
img size, why 380？

### ISSUE THREAD

**Issue by splinter21** [szq0214/MEAL-V2#23]
380不能被32整除，在跑resnet的时候会不会性能受到影响？因为要经过5次下采样，1次maxpooling，4次stride=2卷积
这个模型
MEAL-V2 w/ ResNet50 | 380 | 25.6M | 81.72/95.81

**Comment by szq0214** [comment]
Hi @splinter21 主要为了match teachers的input size，使用相近的resolution比如384，结果差别应该不大。
