### ISSUE TITLE
Is it necessary to apply multiple teacher ensemble?

### ISSUE THREAD

**Issue by anonymoussss** [szq0214/MEAL-V2#25]
Hi, I have a question,

In paper Table 5, you apply  three teacher models to distill the student model. For example, use senet154, resnet152 and their ensembled result as teacher models for a resnet50 student. 

![image](https://user-images.githubusercontent.com/12672787/163125188-b6cb2e31-524a-46b3-ac88-57053703b158.png)

Have you tried distilling a student model using **only the best performing teacher model**（e.g. senet154: Acc@1 81.378）, instead of using ensembled models ? Will a student model distilled from a single model perform worse?

**Comment by szq0214** [comment]
Hi @anonymoussss Yes, using a single teacher of senet154 will lead to worse results than the current teacher ensemble, but we did not test the scenario if the single teacher is stronger than the teacher ensemble.
