### ISSUE TITLE
loss Value

### ISSUE THREAD

**Issue by yukaizhou** [szq0214/MEAL-V2#7]
Hello, thank you very much for your extraordinary work. However, when I change to my own task, the following situation occurs: the value of loss does not decrease. Looking forward to your reply!

Epoch: [46][1/44]	Time 2.27 (2.27)   Data 1.66 (1.66)   G_Loss 6.603 {6.603, 6.603}    D_Loss 0.347 {0.347, 0.347}    T_Loss 0.301 {0.301, 0.301}    Top-1 0.00 {0.00, 0.00}    Top-5 0.00 {0.00, 0.00}    LR 0.00030
Epoch: [46][11/44]	Time 0.66 (0.81)   Data 0.06 (0.20)   G_Loss 6.586 {6.603, 6.603}    D_Loss 0.348 {0.347, 0.347}    T_Loss 0.301 {0.303, 0.303}    Top-1 0.00 {0.00, 0.00}    Top-5 0.00 {0.39, 0.39}    LR 0.00030
Epoch: [46][21/44]	Time 0.65 (0.74)   Data 0.05 (0.13)   G_Loss 6.564 {6.596, 6.596}    D_Loss 0.347 {0.347, 0.347}    T_Loss 0.301 {0.302, 0.302}    Top-1 0.39 {0.02, 0.02}    Top-5 3.12 {0.50, 0.50}    LR 0.00030
Epoch: [46][31/44]	Time 0.66 (0.71)   Data 0.05 (0.11)   G_Loss 6.529 {6.582, 6.582}    D_Loss 0.347 {0.347, 0.347}    T_Loss 0.301 {0.302, 0.302}    Top-1 1.56 {0.10, 0.10}    Top-5 3.12 {0.73, 0.73}    LR 0.00030
Epoch: [46][41/44]	Time 0.66 (0.70)   Data 0.06 (0.09)   G_Loss 6.504 {6.568, 6.568}    D_Loss 0.347 {0.347, 0.347}    T_Loss 0.301 {0.301, 0.301}    Top-1 1.56 {0.25, 0.25}    Top-5 3.12 {1.14, 1.14}    LR 0.00030
Epoch: [46] -- TRAINING SUMMARY	Time 30.68   Data 3.98   G_Loss 6.560     D_Loss 0.347     T_Loss 0.301     Top-1 0.30    Top-5 1.28    
Epoch: [47][1/44]	Time 2.29 (2.29)   Data 1.68 (1.68)   G_Loss 6.598 {6.598, 6.598}    D_Loss 0.347 {0.347, 0.347}    T_Loss 0.314 {0.314, 0.314}    Top-1 0.00 {0.00, 0.00}    Top-5 0.39 {0.39, 0.39}    LR 0.00030
Epoch: [47][11/44]	Time 0.65 (0.82)   Data 0.05 (0.21)   G_Loss 6.587 {6.603, 6.603}    D_Loss 0.347 {0.347, 0.347}    T_Loss 0.301 {0.302, 0.302}    Top-1 0.00 {0.00, 0.00}    Top-5 0.00 {0.28, 0.28}    LR 0.00030
Epoch: [47][21/44]	Time 0.66 (0.74)   Data 0.05 (0.14)   G_Loss 6.606 {6.590, 6.590}    D_Loss 0.347 {0.347, 0.347}    T_Loss 0.301 {0.302, 0.302}    Top-1 0.00 {0.13, 0.13}    Top-5 0.00 {0.67, 0.67}    LR 0.00030
Epoch: [47][31/44]	Time 0.66 (0.72)   Data 0.05 (0.11)   G_Loss 6.563 {6.582, 6.582}    D_Loss 0.347 {0.347, 0.347}    T_Loss 0.301 {0.301, 0.301}    Top-1 0.00 {0.09, 0.09}    Top-5 0.00 {0.71, 0.71}    LR 0.00030
Epoch: [47][41/44]	Time 0.69 (0.70)   Data 0.08 (0.10)   G_Loss 6.486 {6.567, 6.567}    D_Loss 0.347 {0.347, 0.347}    T_Loss 0.301 {0.301, 0.301}    Top-1 0.00 {0.09, 0.09}    Top-5 1.56 {0.99, 0.99}    LR 0.00030
Epoch: [47] -- TRAINING SUMMARY	Time 30.88   Data 4.16   G_Loss 6.560     D_Loss 0.347     T_Loss 0.306     Top-1 0.08    Top-5 1.14    
Epoch: [48][1/44]	Time 2.23 (2.23)   Data 1.62 (1.62)   G_Loss 6.601 {6.601, 6.601}    D_Loss 0.347 {0.347, 0.347}    T_Loss 0.560 {0.560, 0.560}    Top-1 0.00 {0.00, 0.00}    Top-5 0.39 {0.39, 0.39}    LR 0.00030
Epoch: [48][11/44]	Time 0.67 (0.81)   Data 0.06 (0.20)   G_Loss 6.850 {6.653, 6.653}    D_Loss 0.348 {0.347, 0.347}    T_Loss 0.680 {0.821, 0.821}    Top-1 0.00 {0.07, 0.07}    Top-5 0.00 {0.89, 0.89}    LR 0.00030
Epoch: [48][21/44]	Time 0.68 (0.75)   Data 0.07 (0.14)   G_Loss 6.637 {6.657, 6.657}    D_Loss 0.347 {0.347, 0.347}    T_Loss 0.388 {0.653, 0.653}    Top-1 0.00 {0.04, 0.04}    Top-5 0.00 {0.65, 0.65}    LR 0.00030
Epoch: [48][31/44]	Time 0.68 (0.72)   Data 0.07 (0.11)   G_Loss 6.589 {6.640, 6.640}    D_Loss 0.347 {0.348, 0.348}    T_Loss 0.328 {0.563, 0.563}    Top-1 0.00 {0.08, 0.08}    Top-5 0.00 {0.68, 0.68}    LR 0.00030
Epoch: [48][41/44]	Time 0.65 (0.71)   Data 0.05 (0.10)   G_Loss 6.541 {6.622, 6.622}    D_Loss 0.347 {0.348, 0.348}    T_Loss 0.310 {0.502, 0.502}    Top-1 0.00 {0.10, 0.10}    Top-5 1.56 {0.74, 0.74}    LR 0.00030

**Comment by szq0214** [comment]
Hi @yukaizhou, it seems you are training the student from scratch but you choose an extremely small learning rate, I suggest to use a much larger lr like 0.1.
